### ISSUE TITLE
Hi, I want to understand it and explore

### ISSUE THREAD

**Issue by vis2021t** [HMaker/HMaker.github.io#1]
Can u explain or provide me resources or maybe guide me to the understanding of it's working

it will be great if u provide a summary of work

**Comment by vis2021t** [comment]
Why inside CDPRuntimeDomainTest get is being called when it's a dev tools open I'm curious 

why stack gets auto called ?

**Comment by HMaker** [comment]
> Can u explain or provide me resources or maybe guide me to the understanding of it's working

Point to the code you have questions.

> why stack gets auto called ?

On the docstring of `CDPRuntimeDomainTest` you have a link to the chromium code which does that. Chrome buffers console messages when devtools isnt open, so the `stack` will be never accessed. When you open devtools chrome starts serializing all buffered messages, here `stack` is accessed.

The devtools console uses the Devtools Runtime domain, specifically it listens to the [Runtime.consoleAPICalled](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled) events. This event is what causes the leak.

**Comment by kaliiiiiiiiii** [comment]
@HMaker
Thanks for your gread repository!

Seems like I managed to bypass your detections using the following script:
```python
from selenium_driverless import webdriver
import asyncio


async def main():
    options = webdriver.Options()
    async with webdriver.Chrome(options=options) as driver:
        await driver.get('https://hmaker.github.io/selenium-detector/')
        elem = await driver.execute_script('return document.querySelector("#chromedriver-token")')
        await elem.send_keys(await driver.execute_script('return window.token'))
        elem2 = await driver.execute_script('return document.querySelector("#chromedriver-asynctoken")')
        async_token = await driver.execute_async_script('window.getAsyncToken().then(arguments[0])')
        await elem2.send_keys(async_token)
        elem3 = await driver.execute_script('return document.querySelector("#chromedriver-test")')
        await elem3.click()
        print(await driver.title)


asyncio.run(main())
```

note: the script uses features, which are only included in the [dev-branch](https://github.com/kaliiiiiiiiii/Selenium-Driverless/tree/dev)

feel free to check it out & maybe find new ways to detect it:)

<img width="370" alt="image" src="https://github.com/HMaker/HMaker.github.io/assets/89038706/45bc6f4d-5da8-47c0-9a72-8dd00b4b5319">

**Comment by HMaker** [comment]
@kaliiiiiiiiii I see you used pycdp to reimplement the selenium webdriver interface. Yes that works, all my detections here are targeted towards chromedriver.
